name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 수동으로 워크플로우를 실행할 수 있는 옵션
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Docker Buildx 설정 (멀티 플랫폼 빌드 지원)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Docker Hub 로그인
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # 빌드 시간 기반 태그 생성
    - name: Generate build timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
        
    # Docker 이미지 빌드 및 푸시
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mylog:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mylog:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/mylog:${{ steps.timestamp.outputs.timestamp }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mylog:latest
        cache-to: type=inline
        
    # 빌드 결과 정보 출력
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
